### ISSUE TITLE
Replace Domain and relative path

### ISSUE THREAD

**Issue by widoz** [inpsyde/search-and-replace#107]
Replace domain form have two inputs, the search and the replace. 
The first is a `text` type and the latter `url`. 

I think it's better to have the same type but the url one doesn't validate for relative paths. 
I don't know if in this case a relative url is allowed since we are talking about the domain.

**Comment by bueltge** [comment]
Yes, good hint. It is the same type, we change only the string. We should also allow all options, also relative urls.

**Comment by widoz** [comment]
I'll use `text` because seems `url` doesn't allow relatives.
