### ISSUE TITLE
PhpUnit Dependecy and PHP Version

### ISSUE THREAD

**Issue by widoz** [inpsyde/search-and-replace#109]
Currently the plugin define a dependency to phpunit >= 6.3.x but the plugin must be compatible with php 5.6 at least.

I think we have two ways to go.

1. We drop support for php 5.6 that acconding to WordPress statics it's 40.9% (but I think we can support php 5.4 with a little effort).
2. We downgrade the phpunit package version to 5, that according to phpunit documentation his support will ends on February 2, 2018

Due to the wp statistics I think to not drop the support to php 5.6 is the way to go.

>    Problem 1
>
>        phpunit/phpunit 6.3.1 requires php ^7.0 -> your PHP version (5.6.32) does not satisfy that requirement.
>
 >       phpunit/phpunit 6.3.0 requires php ^7.0 -> your PHP version (5.6.32) does not satisfy that requirement.
>
>        Installation request for phpunit/phpunit 6.3.* -> satisfiable by phpunit/phpunit[6.3.0, 6.3.1].

@bueltge Toughts?

**Comment by bueltge** [comment]
You hint is the way, we should not change support smaller 5.6, but we can't also not switch to 7, so that we should switch phpunit version.
Will you do that?

**Comment by bueltge** [comment]
OK, I see now https://github.com/inpsyde/search-and-replace/commit/139a15da3d55483e543ab92b1bbfe57eec22f88b
Thanks.

**Comment by widoz** [comment]
Created a branch https://github.com/inpsyde/search-and-replace/tree/phpunitTests to not commit and push multiple time in master for this kind of issue.

> OK, I see now 139a15d

Yup, let me fix some test and if it's ok we can merge.

**Comment by widoz** [comment]
Tests now pass after @8d4ed49 but build still not https://travis-ci.org/inpsyde/search-and-replace/jobs/318071046

**Comment by widoz** [comment]
Ok some news.

1. I dropped the 5.4 support even from travis. Phpunit 5.7.x require at least php 5.6 so we cannot test it.
2. Removed the composer autoloader from the repo, the issues with the build were because of a missed file no longer exists. So I suggest to not include the autoloader if not in the package. But need advices regarding to introduce a  grunt task to create it.

Now the only things that prevent build to pass is the coding standard. 
To see the latest test see here https://travis-ci.org/inpsyde/search-and-replace/jobs/318203124

All builds fails because of that.

So, if we want to builds to pass we need to fix those errors or remove the phcs from the build process.

**Comment by bueltge** [comment]
Shortly, we should remove phpcs and focus later, that we implement phpcs again.

**Comment by widoz** [comment]
Ok all tests pass and travis is ok. 
Last Build: https://travis-ci.org/inpsyde/search-and-replace/builds/318496661?utm_source=github_status&utm_medium=notification
Last commit: 1ae770d in phpunitTests

I'm going to close this and merge the branch into master.

**Comment by bueltge** [comment]
Thanks @widoz
