### ISSUE TITLE
Search field on find and replace page do not allow to search multi lines 

### ISSUE THREAD

**Issue by bouchaala-sabri** [inpsyde/search-and-replace#119]
So let's say I'm using some page builder or shortcode and I need to replace a module/block on many pages; for example I'm searching this on wp_posts content column :

```
[et_pb_text _builder_version="3.15"]

[wp_forecast]

[/et_pb_text]
```

The actual input text will not allow me to do that as it does not support the newlines. 
A text area is more suitable in this case.

**Comment by bouchaala-sabri** [comment]
https://github.com/inpsyde/search-and-replace/pull/120

**Comment by bueltge** [comment]
Thanks for this feature and PR.

**Comment by bueltge** [comment]
Merged, a public release will be done later, after solid our db diff unit tests. THX.

**Comment by bouchaala-sabri** [comment]
Thanks @bueltge
