### ISSUE TITLE
Miss replace all strings

### ISSUE THREAD

**Issue by lefrankleal** [inpsyde/search-and-replace#125]
I've tried to replace the domain in the search and replace tab but not all the strings were found neither after the first, second and third replace try, just had rerun the search 3 or 4 times but wasnt found so had to do this manually

Thanks

**Comment by bueltge** [comment]
Which version of the plugin? Have you try the last version from github?

**Comment by lefrankleal** [comment]
actually am using the version 3.1.2, i've installed it from the wp store

**Comment by bueltge** [comment]
Please can you try this version, download the zip - https://github.com/bvdv/search-and-replace/releases/download/3.2.0/search-and-replace-3.2.0.zip
Overwrite via FTP your version and test.
Thanks for your feedback

**Comment by bueltge** [comment]
The new version should also fixed them, no problems in all tests. I close them for now and hope after your update in view days it should also works for you.
