### ISSUE TITLE
Warnings coming when upgrading to php 7.2

### ISSUE THREAD

**Issue by rajesh-mobicules** [inpsyde/search-and-replace#126]
Hi,

I upgraded my environment to php 7.2  and when i am running php compatible checker i am getting the below warnings:

Name: Search & Replace
FILE: /var/www/html/wp-content/plugins/search-and-replace/inc/Database/Exporter.php
--------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
--------------------------------------------------------------------------------------------------------
423 | WARNING | Function each() is deprecated since PHP 7.2; Use a foreach loop instead
461 | WARNING | The variable '$php_errormsg' is deprecated since PHP 7.2; Use error_get_last() instead

These are private functions and cant be overridden direct from theme. I dont want to make any change in my plugin directly.

Please let me know if there is upgraded version of this plugin available or when new version with these fixes will be released.

**Comment by bueltge** [comment]
We have build a current test version from the last dev package - maybe you can try them?
Download without composer knowledge her: https://github.com/bvdv/search-and-replace/releases/tag/3.2.0
Thanks for your feedback.

**Comment by bueltge** [comment]
After check inside the code, this two topics a re done and fixed in the next version, there we will publish. The master branch have the right one inside, but needs Composer autoload for testing. I close the issue and will see, that we release in the next view days.
Thanks for your issue, hint!
