### ISSUE TITLE
Wordpress 5 suport

### ISSUE THREAD

**Issue by artmg** [inpsyde/search-and-replace#127]
HI, I wish to evaluate your plugin on a Wordpress 5 site (5.0.3 with php 7.1).

Your [README requirements](https://github.com/inpsyde/search-and-replace/blob/master/README.md#requirements) and [WP Plugin page](https://wordpress.org/plugins/search-and-replace/) suggest that you have tested as far as WP 4.9.9, but not yet WP5+.

1) Do you have known active users already using the plugin on WP5?
2) Are you aware of issues or breaking changes with the new database schema that affect your plugin?
3) For evaulation/testing purposes would I be better off using the last stable release 3.1.2 or release candidate 3.2.0 mentioned in #118 ?

Please let me know whether you would recommend I:

* Download legacy 3.1.2 from the WP plugins page, whether I should 
* take [RC 3.2.0 from](https://github.com/bvdv/search-and-replace/releases) @bvdv or whether I should 
* look for some other dev version to work best with WP5  

Thanks for your support

**Comment by bueltge** [comment]
Hi @artmg 
Please help us and test the new version; they is ready for test, but we havent enough test to publish them. You find the download here: https://github.com/bvdv/search-and-replace/releases/tag/3.2.0
please send feedback in #118 or here in your issue.
Thanks a lot!

**Comment by bueltge** [comment]
I close this issue, the next release is done in view days and all tests on my side are done. Works in WP 5.1-beta 1 and have no issue for newer php version include php 7.2.
Thanks for your issue and feedback.
