### ISSUE TITLE
[tab_replace_domain] Current Prefix not enabled

### ISSUE THREAD

**Issue by derpixler** [inpsyde/search-and-replace#36]
Click on `Change database prefix` the input to change the prefix will not enabled.
![replace domain url www playground dev wordpress](https://cloud.githubusercontent.com/assets/809219/12668066/559dd824-c653-11e5-984b-486950eabe6b.png)

**Comment by bueltge** [comment]
Es soll doch das Feld neuer Prefix aktiv werden, richtig? 
Ich habe die css Klasse am current prefix entfernt, damit das Feld nicht selektiert wird ist. Dieses muss doch bleiben, dachte ich.

**Comment by derpixler** [comment]
Passt schon, ich habe noch geschlafen :)

**Comment by bueltge** [comment]
😁

**Comment by s-hinse** [comment]
Der "current table name" soll gar kein <input> sein, der ist nur zur Information und wird nicht weiterverarbeitet. Ich hatte vergessen, den <label>-tag zu entfernen.

**Comment by bueltge** [comment]
@s-hinse Ich habe ein Input daraus gemacht, welches aber immer inaktiv ist. Sieht so besser aus, UI gleichmäßig homogen.
Aus meiner Sicht also kein ToDo.

**Comment by derpixler** [comment]
@bueltg jetzt verstehe ich auch warum ich das als Fehler empfunden habe! Ich bin dafür kein input zu verwenden. Das input impliziert - hier kann ich etwas ändern, was aber nicht so ist. Ich bin irritiert, halte es für fehlerhaft, es entsteht Unsicherheit ...

**Comment by bueltge** [comment]
Deswegen ist es ja disabled, du kannst nix ändern. Du hast aber ein sauberes UI.
