### ISSUE TITLE
Add Travis Support for run UnitTests 

### ISSUE THREAD

**Issue by bueltge** [inpsyde/search-and-replace#38]
like https://github.com/inpsyde/multilingual-press/blob/master/.travis.yml

our account: https://travis-ci.org/inpsyde/

**Comment by derpixler** [comment]
The basic travis support for travis was added. See https://github.com/inpsyde/search-and-replace/commit/6d0e9b12d23a7e7a2a5bda2dcee34e50ce080ab5
