### ISSUE TITLE
search for html code gives no results

### ISSUE THREAD

**Issue by thesatman** [inpsyde/search-and-replace#40]
Hi,

In my wp_posts there is a field called post_content. The HTML code of the page created in WP is stored here. I need to update multiple pages with a few changes to the HTML code, and have two options. Check every page in WP editor, one-by-one, and change the code. Or, use S&R. What I am trying now is to do a Dry Run and search for:

image_alt="Some Text Here" link_type="no_link" 

and eventually change that to:

image_alt="Some Text Here" link_type="page" single_item="257" open_in="current_browser"

However, when I do a search for the first criteria mentioned above, no search pattern is found. The search entered is now displayed as:

image_alt=\

It looks like the " sign is causing the problem. How can I do a succesfull S&R ?

Wordpress 4.4.2
S&R Version 3.0.0

**Comment by derpixler** [comment]
i´ve merge and tested the [fix](https://github.com/s-hinse/search-and-replace/commit/3fe982700c1c3bdbd995ab4d79cb8c77df6a3218) from @s-hinse. Searchpattern with quotes will now replaced.
