### ISSUE TITLE
Composer: Use PSR-Autoloading

### ISSUE THREAD

**Issue by Chrico** [inpsyde/search-and-replace#45]
The autoloading class `Inpsyde\searchReplace\inc\Autoloader` could be replaced by composer and PSR-Autoloading. Just include the `/vendor/autoload.php` after `composer install`.

**Comment by Chrico** [comment]
Why closing? Currently you're using PSR-Composer-Autoloader _and_ Requiste (which should be loaded via composer and not comitted to the Repository..) @derpixler

**Comment by bueltge** [comment]
Reference to c4fa2aff856602b837faaadf2f5591042ecc2be1
