### ISSUE TITLE
Warning: preg_match_all();

### ISSUE THREAD

**Issue by derpixler** [inpsyde/search-and-replace#49]
User at the wp.org reported the following waring,
>[16-Feb-2016 21:03:25 UTC] PHP Warning: preg_match_all(): Compilation failed: missing terminating ] for character class at offset 27 in ~/wp-content/plugins/search-and-replace/inc/Admin.php on line 290
_https://wordpress.org/support/topic/php-errors-69#post-8044179_

**Comment by grzegorz-janoszka** [comment]
I tried browsing via options and doing dry runs and I couldn't reproduce such log messages now.
The only thing I didn't do was a real DB search and replace, so I can assume it happened during real operations.

**Comment by grzegorz-janoszka** [comment]
The number and timing of such errors in the logs strongly suggests it happened during live operation on the DB.

**Comment by derpixler** [comment]
i can't no more repoduce this error.
