### ISSUE TITLE
wrong translation in "Tools" menu

### ISSUE THREAD

**Issue by svebal** [inpsyde/search-and-replace#57]
In _"Tools"_ menu a wrong German translation is displayed:

![bildschirmfoto](https://cloud.githubusercontent.com/assets/809512/14297778/f63d0c52-fb80-11e5-8240-e6a61024fe29.png)

Should be _"Suchen & Ersetzen"_ or similiar

**Comment by derpixler** [comment]
tested

**Comment by bueltge** [comment]
Thanks for the hint @svebal :+1:
