### ISSUE TITLE
SQL Error on import

### ISSUE THREAD

**Issue by derpixler** [inpsyde/search-and-replace#58]
In exported databases we create tables wit the following sql.

``` sql
CREATE TABLE `i_5_postmeta` (
  `meta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `post_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `meta_key` varchar(255) DEFAULT NULL,
  `meta_value` longtext,
  PRIMARY KEY (`meta_id`),
  KEY `post_id` (`post_id`),
  KEY `meta_key` (`meta_key`(191))
) TYPE=InnoDB AUTO_INCREMENT=309 ;
```

On import this throws a error

```
#1064 - You have an error in your SQL syntax; check the manual that corresponds
to your MySQL server version for the right syntax to use near 
'TYPE=InnoDB AUTO_INCREMENT=19815' at line 13
```

---

**Solution:** Replace `TYPE=InnoDB` with `Engine=InnoDB`

**Comment by derpixler** [comment]
The `Create Table` statement will create at `inc/Database/Manager.php` and here we use mysql to create the statement.

```php
/**
	 * returns a SQL CREATE TABLE Statement for the table provided in $table
	 *
	 * @param $table String The Name of the table we want to create the statement for.
	 *
	 * @return string
	 */
	public function get_create_table_statement( $table ) {
		return $this->wpdb->get_results( "SHOW CREATE TABLE $table", ARRAY_N );
	}
```

**Comment by derpixler** [comment]
We take a looke here and move this to 3.2

**Comment by devbanana** [comment]
This plugin uses SHOW CREATE TABLE to get the MySQL syntax, so I don't think messing with the output would be a good idea. Perhaps your table was created with an older MySQL version, so the older syntax is still shown? TYPE=InnoDB was deprecated in MySQL 5.1.

I'm going to close this since it is up to the SQL server to show the right SQL syntax.
