### ISSUE TITLE
Use existing tool for core functionality

### ISSUE THREAD

**Issue by s-hinse** [inpsyde/search-and-replace#6]
There are some tools around, that do a good search&replace-job (e. g. https://interconnectit.com/products/search-and-replace-for-wordpress-databases/) so why not take one of them and wrap an UI for wordpress around it?

**Comment by bueltge** [comment]
Is useful and have a lot of hacks to fixing problems, but see #1 for a simple useful class, that we should use, maybe rewrite for a better testing, but the methods are useful.

**Comment by derpixler** [comment]
solved in `version-2`see #1
