### ISSUE TITLE
The menu of the plugin splitted in its single page views

### ISSUE THREAD

**Issue by derpixler** [inpsyde/search-and-replace#62]
Hey,

I've installed v. 3.1.0 with WP-Version 4.5 and have the following issue.
The menu of the plugin seems to be splitted in its single page views. See picture for more.
The issue was before the update to WP 4.5, too:

http://abload.de/img/suchen_und_ersetzen5ziuc.png

I appreciate your help and thank you in advance,

Vince

**Comment by Chrico** [comment]
This should be removed by following command: https://github.com/inpsyde/search-and-replace/blob/83c6fc88ef20ae9359351c98563666794c15691f/inc/Plugin.php#L44

Callback for this hook is here: https://github.com/inpsyde/search-and-replace/blob/83c6fc88ef20ae9359351c98563666794c15691f/inc/Page/Manager.php#L84

**Comment by derpixler** [comment]
cant reproduce anymore on 4.5 and .4.4
