### ISSUE TITLE
Use GZ compression for Save changes to database

### ISSUE THREAD

**Issue by Vanvox** [inpsyde/search-and-replace#64]
On the tab _Search & Replace_ you can select _Use GZ compression_ if you choose to _Save changes to database_. 
GZ Compression should only be available for _Export SQL file with changes_.

![2016-05-03_08-09-36](https://cloud.githubusercontent.com/assets/9631681/14975915/ff0f7626-1106-11e6-8a44-429c4e01e1e7.png)

**Comment by devbanana** [comment]
Fixed by c1b074c0581399ee2393519ab321e86da65d70e5
