### ISSUE TITLE
Deactivate "Search for" input field on tab Replace Domain URL

### ISSUE THREAD

**Issue by Vanvox** [inpsyde/search-and-replace#65]
On the tab _Replace Domain URL_ the field _Search for_ should be deactivated because it is not intended to input something in this field. It should just show the url of the current wordpress install.

**Comment by Bluxart** [comment]
I think this option need to be optional, because for my envoriment, I need to search external strings in the current installation and replace.

**Comment by derpixler** [comment]
@Bluxart if you would search external string, you can do this on the default Search & Replace Tap.
