### ISSUE TITLE
switch to deactivate MaxExecutionTime

### ISSUE THREAD

**Issue by derpixler** [inpsyde/search-and-replace#66]
We have reported security error on systems where `set_time_limit()`is deactivated at the 'php.ini`.
To nevertheless get the plugin working we have to implement a option to switch off MaxExecutionTime.

> Has been disabled for security reasons in ....../wp-content/plugins/search-and-replace/inc/Service/MaxExecutionTime.php on line 27

**Comment by cfoellmann** [comment]
why did you close this?
I got the same warning popping up

**Comment by bueltge** [comment]
In which version, the last checkout of the branch or the version from w.org?

**Comment by cfoellmann** [comment]
Shit. Sorry.
Yes it is the wp.org version. Just assumed that this old issue should done in a release version

**Comment by bueltge** [comment]
However we are really thankful for tests. Maybe you use thos Version and get us feedback?
