### ISSUE TITLE
Parse error: syntax error, unexpected T_STRING in inspyde-search-replace.php on line 16

### ISSUE THREAD

**Issue by juherr** [inpsyde/search-and-replace#70]
After the upgrade of my wordpress to 4.6.1, I'm not able to activate the plugin and I have the following message instead:

> Parse error: syntax error, unexpected T_STRING in [...]/wordpress/wp-content/plugins/search-and-replace/inspyde-search-replace.php on line 16

**Comment by derpixler** [comment]
Dublicted to #67

**Comment by juherr** [comment]
Oops, sorry!

**Comment by derpixler** [comment]
no worries :)
