### ISSUE TITLE
Adding a prompt for “Are you sure?” before do danger things

### ISSUE THREAD

**Issue by derpixler** [inpsyde/search-and-replace#71]
We want make sure no one can screw up their install. But that’s the entire point of the dry run. If anyone uses the plugin and doesn’t back up their db first, then that’s their own fault. Even adding a prompt for “Are you sure?” would be better than requiring a table prefix change, export and import procedure.

**Comment by devbanana** [comment]
In commit 28479b64ee9d3c8610d911fbe2705d7c95c87c2a, exactly that kind of message is added when the user is trying to change site URL. I don't personally think a message should be added for all search/replace operations, except the ones that could hurt the site, such as the one I mentioned.
