### ISSUE TITLE
Clarify how the "Replace URL" function works..

### ISSUE THREAD

**Issue by SherylHohman** [inpsyde/search-and-replace#74]
This description is unclear to me: 

`If you want to migrate your site to another domain, enter the new URL in the field "Replace with" and create a backup of your database by clicking "Do Replace Domain/Url".`

- Does it update the current database ?   
- If so, is the "backup" it's creating a backup of the Before-the-URL-change backup?  Or a copy of the post-URL change? 
- Or Does this instead create a copy of the current database, perform the URL change on this copy, and make the changed-URL-copy available for download ?   (safest)

If the latter, the following wording would make this more clear.

`If you want to migrate your site to another domain, enter the new URL in the field "Replace with".
To download a copy of your database with the Updated/New URL, Click "Do Replace Domain/Url".`

If the the URL change takes place on the current database, It would be helpful to Warn Us, or at least be clear, that our current database will be permanently altered.  Also, it could then clarify which version of the database will be available for download (if any).

Thank You for clarifying.. :-)

**Comment by devbanana** [comment]
@SherylHohman I have modified the text as such:

> If you want to migrate your site to another domain, enter the new URL in the field "Replace with" and click "Do Replace Domain/Url". You can then download a database backup containing the new URL.

Hopefully this improves understanding. I agree it was perhaps a bit ambiguous.
