### ISSUE TITLE
SQL dump with Wordfence are not valid

### ISSUE THREAD

**Issue by allaire** [inpsyde/search-and-replace#77]
Hi,

Wordfence seems to put Hex data in the database, and this plugin does not correctly generate the dump.

WP Migrate DB was able to do it correctly, see: https://github.com/deliciousbrains/wp-migrate-db/blob/6fb5ad6b7c098cd6dace722b8485003cb090ca94/class/wpmdb.php#L2422-L2429

**Comment by gerbilOFdoom** [comment]
Could you provide an example of the hex data that does not process properly? I've been thinking about using Wordfence in the future so I'll try to fix the issue.

**Comment by allaire** [comment]
@gerbilOFdoom I cannot sorry :/ But just install it for a day or two and export it, you'll see 👍

**Comment by devbanana** [comment]
This should now be fixed. Please let me know if not.
