### ISSUE TITLE
Replace Domain URL: Search for disabled

### ISSUE THREAD

**Issue by Bluxart** [inpsyde/search-and-replace#78]
Hi, I see now the plugin disabled the search for in Replace Domain URL.

It's possible re-enabled it ( with an activable options ), bacause I need to change the url ( external source ) for import some media images, and I need set a different URL and replace with new, but with last update now it is not possible.

Thanks.

**Comment by derpixler** [comment]
@Bluxart of cours feel free to implement a filter on https://github.com/inpsyde/search-and-replace/blob/master/inc/templates/replace_domain.php#L21

Like ```....rch" type="text" [FILTER THE DISABLE VALUE] name="search" value="<?php echo g.....```
