### ISSUE TITLE
Unknown: Cannot use output buffering in output buffering display handlers

### ISSUE THREAD

**Issue by moisty70** [inpsyde/search-and-replace#79]
Hi,
I got this error and don't know how to start searching for were the problem is
Unknown: Cannot use output buffering in output buffering display handlers in <b>Unknown</b> on line <b>0</b><br />

For example when I click on backup database that is the content of the file, also when I try to export changes.

**Comment by gerbilOFdoom** [comment]
What plugins do you have installed? What version of Wordpress? What version of PHP?

**Comment by moisty70** [comment]
Sorry but I cannot help you now, I guess I solved the problem with another plugin, I don't even remember which WP installation the problem came from.
