### ISSUE TITLE
export / import of a multisite subsite

### ISSUE THREAD

**Issue by s-hinse** [inpsyde/search-and-replace#8]
- [ ] Push/pull a subsite to a single site install
- [ ] Push/pull a single site install  into a multisite install as a subsite
- [ ] Push/pull a subsite  from one multisite install to another multisite install
  see: https://deliciousbrains.com/wp-migrate-db-pro/doc/multisite-tools-addon/?utm_source=wordpress.org&utm_medium=web&utm_content=desc&utm_campaign=freeplugin

**Comment by derpixler** [comment]
i think this is a good idea but not in case of this Plugin.

**Comment by devbanana** [comment]
I think it would overly complicate this plugin. I agree with @derpixler
