### ISSUE TITLE
Modifying Guid column when editing _posts table

### ISSUE THREAD

**Issue by dan-eth** [inpsyde/search-and-replace#80]
Steps to replicate the issue:
1/Activate Search and Replace on multisite
2/Conduct dry-run search on _posts table 
3/Click on View results and check the columns.
4/Review the 4th column (both guid and post_content are listed)
*This issue doesn't happen when searching for _postmeta table. 

Hello Sirs,

I run into trouble while updating the database today. I am yet diagnosing the cause of the problem and retracing my steps.

In the process, I noticed that the Search & Replace DB plugin includes the Guid column when asked to search and replace the _posts table.

**Comment by dan-eth** [comment]
Is this unclear? Or what?
I thought this is a major flaw and contrary to WordPress's caution not to touch the Guid column.

**Comment by bueltge** [comment]
No, it is not possible for us to get feedback in 24h on each project. It is open source to get helping hands also from others.

**Comment by dan-eth** [comment]
No no. 
I was expecting this to raise red flag and would be my first bug report to Github. :)

Take your time.
I am going to use wp-cli anyway.

**Comment by bueltge** [comment]
@dan-eth I'm sorry. But you should understand, it is not possible for us to read each issue to each project adhoc. We need time and mind to read, understand it and give feedback. But if you familiar with wp-cli, use it, it much more solid in this context, need no UI.

**Comment by gerbilOFdoom** [comment]
@bueltge I've verified with the Wordpress Codex that the GUID column must always be left alone. To that end I've created pull request #83 which prevents edits to the GUID column.

**Comment by devbanana** [comment]
Thanks for the fix. It's been merged.
