### ISSUE TITLE
undefined function filter_input(), version 3.1.2

### ISSUE THREAD

**Issue by daviddpd** [inpsyde/search-and-replace#81]
Trying this out ... and the search/replace just hangs - no output, just a blank screen.  It looks like a function is missing from the latest build.

FreeBSD 11.0-RELEASE-p8, PHP 5.6.30

search-and-replace Version 3.1.2 

`PHP Fatal error:  Call to undefined function Inpsyde\\SearchReplace\\Page\\filter_input() in /usr/local/www/wordpress/wp-content/plugins/search-and-replace/inc/Page/Manager.php on line 36, referer: https://{SITE}/blog/wp-admin/tools.php?page=search-replace`

**Comment by daviddpd** [comment]
Sorry - FreeBSD issue ... filter extension not installed `pkg install php56-filter`

**Comment by bueltge** [comment]
Thanks for clarification.
