### ISSUE TITLE
Too helpful

### ISSUE THREAD

**Issue by mskogly** [inpsyde/search-and-replace#84]
Your search contains your current site url. Replacing your site url will most likely cause your site to break. If you want to change the URL (and you know what you doing), please use the export function and make sure you backup your database before reimporting the changed SQL.

Is there a way to override this? I upgraded from an earlier version today, and suddenly the plugin is useless. 

I'm doing a preparation for switching to https, so I need to replace"http://mysite.com" with "//mysite.com"

**Comment by mskogly** [comment]
Downgraded to a previous version :)

**Comment by devbanana** [comment]
Hi @mskogly. I agree that could be annoying. Perhaps just an “Are you sure?” message would be preferable?
