### ISSUE TITLE
Unserialization fails with serialized custom PHP objects

### ISSUE THREAD

**Issue by ryantang333** [inpsyde/search-and-replace#93]
When using unserialize on a value that is a serialized PHP object that is not defined will result in a __PHP_Incomplete_Class error. In my scenario, a third party plugin stored a custom class as serialized data in our db. I don't care about unserializing it because I won't be using it, so my suggestion is to pass false as the second parameter as per the [documentation](http://php.net/manual/en/function.unserialize.php). However, the caveat is that the data will be completely ignored, so if a user has data in their database that is a serialized PHP Class that they themselves defined, it will not be serialized unless the class was properly instantiated and accessible when running the search and replace.

**Comment by bueltge** [comment]
Is that fix with #94 ? 
Thanks for your helping hands! :+1:

**Comment by ryantang333** [comment]
@bueltge yep! No problem!

**Comment by bueltge** [comment]
Fixed in #94
