### ISSUE TITLE
Avoid markup within the translation functions

### ISSUE THREAD

**Issue by widoz** [inpsyde/search-and-replace#99]
Can we remove markup from the translation strings like: 

`'Look at our other <a href="%s">free WordPress plugins</a>.'` and use the `sprintf`, `printf` functions instead? 

More info here http://ottopress.com/2012/internationalization-youre-probably-doing-it-wrong/

**Comment by bueltge** [comment]
Yes, we should do. Currently was a effort topic, that we leave this. But please, feel free to change this to a solid and secure solution.
